<?php $title="WD | Carpinteria Perfil";  include "components/head.php"; ?>
	<div class="wd-wrapper">
		<?php  include "components/menu/index.php"; ?>
		<div class="wd-wrapper__max">
			<main class="wd-main">
				<?php
					$stage_location = 'right';
					$stage_class = 'gray';
					$stage_title = 'Wood & Design';
					include "components/stage/index.php";

					$pleca = 'Obejtivos generales del plan de estudio';
					include "components/pleca/index.php";
					$review = 'true';
					$preview = 'FORMAR ESPECIALISTAS  EN LA INDUSTRÍA DE LA MADERA CON CONOCIMIENTOS TEÓRICOS-INTERDISCIPLINARIOS, METODOLÓGICOS E INSTRUMENTALES, ASÍ COMO HABILIDADES Y ACTITUDES QUE LES PERMITAN PRESTAR SUS SERVICIOS EN CUALQUIER TIPO DE ORGANIZACIÓN CON EL FIN DE QUE INCIDAN EN LAS TRANSFORMACIONES DE LOS ÁMBITOS DE LA INDUSTRIA MADERERA CON SENTIDO ÉTICO Y DE VINCULACIÓN, TANTO CON LA SOCIEDAD COMO CON LAS ORGANIZACIONES, PARA LA MEJORA INTEGRAL QUE EL MERCADO DEMANDE EN CUALQUIER NIVEL O ÁREA, CON MIRAS AL BENEFICIO DE LOS ESTUDIANTES, LA SOCIEDAD Y EL PAÍS.';
					include "components/preview/index.php";

					$pleca = 'Ingreso';
					include "components/pleca/index.php";
					$review = 'true';
					$preview = 'EL CANDIDATO DEBE TENER:<br/>
								1.- HABILIDAD PARA COMUNICARSE APROPIADAMENTE E INTERPRETAR INSTRUCCIONES ESCRITAS Y VERBALES.<br/>
								2.- RAZONAMIENTO FORMAL QUE LE FACILITE LA RESOLUCIÓN DE PROBLEMAS LÓGICOS Y COTIDIANOS.<br/>
								3.-DISPONIBILIDAD PARA EL TRABAJO EN EQUIPO Y CON VALORES UNIVERSALES, CAPAZ DE CONSTRUIR SU PROPIO CONOCIMIENTO.<br/>
								4.- SENCIBILIDAD A LA RESOLUCIÓN DE ASPECTOS ECOLÓGICOS Y DE PROTECCIÓN AL AMBIENTE. <br/>
								5.-CONOCIMIENTOS DE MATEMÁTICAS BÁSICAS Y EL MANEJO DE INSTRUMENTOS DE CÁLCULO.';
					include "components/preview/index.php";

					$pleca = 'Egreso';
					include "components/pleca/index.php";
					$review = 'true';
					$preview = 'COMPRENDER EL CONTEXTO SOCIAL DE LA CARPINTERÍA, ASÍ COMO SUS FUNDAMENTOS HISTÓRICOS  ECONÓMICOS, TANTO A NIVEL NACIONAL COMO MUNDIAL. <br/><br/>
								PROPONER ESTRATEGIAS INNOVADORAS DE INTERVENCIÓN QUE PROPICIEN CAMBIOS EN EL MERCADO DE LA MADERA PARA EL BENEFICIO DE TODOS LOS ACTORES QUE INTERVIENEN EN ÉL, LA SOCIEDAD Y EL PAÍS.<br/><br/>
								COMPRENDER Y APLICAR LAS NUEVAS TECNOLOGÍAS DE LA COMUNICACIÓN, DISEÑO, ELABORACIÓN Y CONSTRUCCIÓN, COMO HERRAMIENTAS DE APOYO   PARA PROPICIAR UNA MEJOR COBERTURA DE  LA INDUSTRIA MADEDERA.<br/><br/>
								DESARROLLAR INVESTIGACIONES TANTO CUALITATIVAS COMO CUANTITATIVAS EN LAS ÁREAS ADMINISTRATIVA, SECTOR COMERCIAL, USO, APLICACIÓN DE DIVERSAS MADERAS; ASÍ COMO HERRAMIENTAS Y PRODUCTOS DIVERSOS  PARA SOLUCIONAR PROBLEMAS, DESARROLLAR, DISEÑAR Y OPERAR NUEVAS ALTERNATIVAS  O QUE PROPICIEN EL CRECIMIENTO, LA INNOVACIÓN Y LA CALIDAD DE LA INDUSTRIA MADERERA Y/O DE  LA CARPINTERÍA DE CUALQUIER NIVEL.<br/>
								EJERCER SU QUEHACER PROFESIONAL CON RESPONSABILIDAD, ÉTICA PROFESIONAL Y VOCACIÓN DE SERVICIO.';
					include "components/preview/index.php";
					include "components/foo/index.php";
				?>
			</main>
		</div>
	</div>
 <?php  include "components/footer.php";
